<!-- Tensor -->
3차원으로 구성된 데이터를 텐서라고 한다.
다만 실제로는 1차원 이상의 데이터를 모두 텐서라고 표현한다.
<!-- Numpy -->
상세한 숫자를 다루는 분야에 쓰이는 라이브러리이며 가장 기본이 되는 자료형은 numpy array.

In [2]:
import numpy as np
#Rank 1
a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a)
a[-1] = -1
print(a)
#Rank 2
b = np.array([[1,2,3], [4,5,6]])
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

<class 'numpy.ndarray'>
(3,)
[1 2 3]
[ 1  2 -1]
(2, 3)
1 2 4


numpy는 기재된 숫자에 따라 타입을 추론한다.
강제로 타입을 지정할 수도 있다.

In [3]:
x = np.array([1, 2])
print(x.dtype)
x = np.array([1.0, 2.0])
print(x.dtype)
x = np.array([1, 2], dtype=np.int64)
print(x.dtype)

int64
float64
int64


사칙연산 부호를 이용할 수 있다.
*는 elementalwise 곱이다.

In [4]:
x = np.array([[1, 2], [3, 4]], dtype=np.float64)
y = np.array([[5, 6], [7, 8]], dtype=np.float64)
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y)) #elementwise. not dot product
print(np.divide(x, y))
print(np.sqrt(x))

[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[1.         1.41421356]
 [1.73205081 2.        ]]


행렬곱을 수행하려면 아래와 같이 dot 연산을 사용해야 한다.

In [5]:
v = np.array([9, 10])
w = np.array([11, 12])
print(np.dot(v, w))
print(np.dot(x, v))

219
[29. 67.]


<!-- PyTorch -->
PyTorch, 줄여서 토치라고 하겠다.
토치는 GPU에서 딥러닝 관련 작업을 수행하기 용이하다.
행렬 연산은 대부분 병렬화가 가능하므로 코어 수가 많을수록 유리하기 때문!
-> 각각 행과 열에 대한 곱은 서로 다른 코어에서 계산이 가능하다.
torch.tensor() 리스트 혹은 numpy array를 입력해 텐서를 생성할 수 있다.

In [6]:
import torch
t = torch.FloatTensor([1, 2, 3, 4, 5, 6])
print(t)
print(t.dim())
print(t.shape)
print(t.size())
print(t.dtype)

tensor([1., 2., 3., 4., 5., 6.])
1
torch.Size([6])
torch.Size([6])
torch.float32


텐서의 인덱싱 및 슬라이싱도 가능하다.
n차원에서 슬라이싱을 수행할 때는 **, 를 써서 각 차원 간의 슬라이싱 정보를 종합하여야 한다.**

In [28]:
print(t[2:5], t[4:-1])
print(t[:2], t[3:])
t = torch.FloatTensor([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9],
                       [10, 11, 12]])
print(t[:, 1])
print(t[:][1])

tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]]) tensor([], size=(0, 3))
tensor([[1., 2., 3.],
        [4., 5., 6.]]) tensor([[10., 11., 12.]])
tensor([ 2.,  5.,  8., 11.])
tensor([4., 5., 6.])


<!-- Broadcasting -->
텐서끼리의 사칙연산은 기본적으로 두 텐서의 셰입이 같아야 하지만, 그렇지 않아도 가능하도록 텐서 크기를 맞추고 값을 복사하여 채워넣는 기능을 브로드캐스팅이라고 한다.
잘 파악하고 이용하면 편리하지만, **의도치 않은 브로드캐스팅이 있을 수 있기 때문에** 스칼라 데이터에 대해서만 브로드캐스팅 기능을 추천한다.

In [8]:
m1 = torch.FloatTensor([1, 2])
m2 = torch.FloatTensor([3]) # [3] -> [3, 3]
print(m1 + m2)

tensor([4., 5.])


텐서 사이에 *를 사용하거나 mul 메서드를 통해 연산을 수행하면 elementwise 곱이 수행된다.
matmul 메서드를 통해 연산을 수행하면 행렬곱이 수행된다.

In [ ]:
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[4, 5], [6, 7]])
print(m1.mul(m2))
m2 = torch.FloatTensor([[1], [2]])
print(m1.matmul(m2))

.mean() 메서드를 통해 텐서 내 값의 평균을 구한다.
기본적으로 스칼라 값을 갖는 텐서로 출력된다. 이를 파이썬 변수 형태로 바꾸려면 .item()메서드를 사용.
sum()메서드로 합계를 구한다. 사용 방식은 mean과 동일하다.

In [18]:
t = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(t.mean())
print(t.mean().item())
print(t.mean(dim=0))
print(t.mean(dim=1))
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1))
print(t.sum(dim=-1))

tensor(3.5000)
3.5
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])
tensor(21.)
tensor([5., 7., 9.])
tensor([ 6., 15.])
tensor([ 6., 15.])


max()메서드로 최대값을 구한다.
여기도 dim 정보를 입력 가능하며 이 때는 **최대값 뿐만 아니라 해당 최대값의 인덱스 정보 또한 반환된다.**

In [19]:
print(t.max(dim=0))

torch.return_types.max(
values=tensor([4., 5., 6.]),
indices=tensor([1, 1, 1]))


view()메서드를 통해 텐서 요소들을 유지하며 모양을 변경한다.
-1의 값을 갖는 인수는 view()메서드 안에서 단 한번 사용할 수 있으며, **-1이 입력된 차원은 토치에서 추론하여 크기를 맞추라는 것으로 해석됨**

In [24]:
print(t.view(-1, 1))
print(t.view(-1, 1).shape)
print(t.view(-1, 6))
print(t.view(-1, 6).shape)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.]])
torch.Size([6, 1])
tensor([[1., 2., 3., 4., 5., 6.]])
torch.Size([1, 6])


squeeze()메서드는 텐서를 눌러서 크기가 1인 차원을 모두 제거한다.
unsqueeze()메서드는 입력받은 인덱스에 크기가 1인 차원을 추가한다.

In [25]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)
print(ft.squeeze())
print(ft.squeeze().shape)
print(ft.unsqueeze(0))
print(ft.unsqueeze(0).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])
tensor([0., 1., 2.])
torch.Size([3])
tensor([[[0.],
         [1.],
         [2.]]])
torch.Size([1, 3, 1])


view(), squeeze(), unsqueeze() 모두 텐서의 요소들을 그대로 유지하며 shape을 바꾸는 기능을 한다. view()가 모든 기능을 수행할 수 있으나, 크기가 1인 차원을 다루는 일이 자주 있기 때문에 메서드가 존재한다.

각 텐서 타입 이름에 해당하는 메서드를 통해 텐서의 타입을 변경 가능하다.

In [ ]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)
print(lt.float())
print(lt.double())

tensor([1, 2, 3, 4])
tensor([1., 2., 3., 4.])
tensor([1., 2., 3., 4.], dtype=torch.float64)


torch.cat() 함수를 통해 텐서끼리 연결할 수 있다.
**어떤 인덱스의 차원을 연결할 것인지를 dim 매개변수를 통해 입력해주어야 한다.**

In [ ]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


torch.one_like(), torch.zeros_like()함수를 통해 입력받는 텐서의 shape과 **똑같은 shape을 가지며 1 혹은 0으로 채워진 텐서**를 생성 가능하다.

In [ ]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)
print(torch.ones_like(x))
print(torch.zeros_like(x))

tensor([[0., 1., 2.],
        [2., 1., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


torch.ones(), torch.zeros()함수를 이용해 **view()메서드에 입력하듯 shape 정보를 입력**하여 해당 shape을 1 혹은 0으로 채워진 텐서를 생성할 수 있다.

In [ ]:
print(torch.ones(2, 3))
print(torch.zeros(3, 2))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
